
- name: install DHCP service
  yum:
    name:
      - dhcp-server
    state: present
  become: yes
  tags: dhcp

- name: Create DHCP config
  template:
    src: dhcpd.conf.j2
    dest: /etc/dhcp/dhcpd.conf
  become: yes
  notify: Restart DHCP Server
  tags: dhcp
